@server = http://localhost:8000
@api = http://localhost:8000/api

###
GET {{server}}

###
GET {{api}}


###
### CONTAINER
###

###
GET {{api}}/container?sse=false

###
GET {{api}}/container?sse=true
  
###
### VOLUME
###
  
###
GET {{api}}/volume

###
### IMAGE
###

###
GET {{api}}/image

###
### CONTEXT
###

###
### AUTH
###