@server = http://localhost:8000
@api = http://localhost:8000/api

###
GET {{server}}

###
GET {{api}}

##################
######### CONTAINER
##################

###
GET {{api}}/container?sse=false

###
GET {{api}}/container?sse=true
  
##################
######### IMAGE
##################

###
GET {{api}}/image

##################
######### NETWORK
##################

###
GET {{api}}/network

##################
######### VOLUME
##################
  
###
GET {{api}}/volume
 
##################
######### SYSTEM
################## 

###
GET {{api}}/system/info

###
GET {{api}}/system/disk-usage
 
###
GET {{api}}/system/ping
  
##################
######### AUTH
##################

###
GET {{api}}/user

###  
POST {{api}}/user
Content-Type: application/json

{
  "Name": "John Doe", 
  "email": "john@gmail.com"
}
 
###  
POST {{api}}/user/1
Content-Type: application/json

{
  "Name": "John Doe2", 
}
 
###   
DELETE {{api}}/user/2